'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { Code2, Database, Terminal, Zap, ArrowRight, Server, Globe } from 'lucide-react';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { atomDark } from 'react-syntax-highlighter/dist/esm/styles/prism';
import Navbar from '@/components/Navbar';
import BackgroundEffect from '@/components/BackgroundEffect';

const PHP_EXAMPLE = `<?php
// DualMind AI OS - Autogenerated PHP API
declare(strict_types=1);

namespace App\\Http\\Controllers;

use App\\Models\\Cognition;
use Illuminate\\Http\\JsonResponse;

class IntelligenceController extends Controller
{
    /**
     * Synthesize insights via DualMind Orchestrator
     */
    public function synthesize(Request $request): JsonResponse
    {
        $query = $request->validate([
            'prompt' => 'required|string|max:2000',
            'depth'  => 'sometimes|in:fast,deep'
        ]);

        $orchestrator = app()->make('dualmind.orchestrator');
        $plan = $orchestrator->generatePlan($query['prompt']);
        
        return response()->json([
            'status' => 'success',
            'plan' => $plan,
            'timestamp' => now()->toIso8601String()
        ]);
    }
}
`;

const QUICK_ACTIONS = [
  {
    title: "Generate PHP API",
    description: "Instantly spin up a full RESTful API with validation, controllers, and routing.",
    icon: <Server className="w-6 h-6 text-accent-cyan" />
  },
  {
    title: "Create Laravel Backend",
    description: "Scaffold an entire Laravel monolith connected to DualMind AI OS.",
    icon: <Code2 className="w-6 h-6 text-accent-purple" />
  },
  {
    title: "Optimize PHP Query",
    description: "Analyze slow PDO/Eloquent queries and rewrite them for extreme performance.",
    icon: <Zap className="w-6 h-6 text-yellow-400" />
  }
];

export default function PhpShowcasePage() {
  return (
    <main className="relative min-h-screen bg-[#050B14] overflow-hidden selection:bg-accent-cyan/30">
      <BackgroundEffect />
      <Navbar />
      
      <div className="relative z-10 container mx-auto px-6 pt-32 pb-24">
        {/* Header Section */}
        <div className="text-center max-w-3xl mx-auto mb-20">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, ease: "easeOut" }}
          >
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-accent-cyan/10 border border-accent-cyan/20 text-accent-cyan text-sm font-medium mb-6 backdrop-blur-md">
              <Database className="w-4 h-4" />
              <span>Native Ecosystem Support</span>
            </div>
            <h1 className="text-5xl md:text-7xl font-bold mb-6 tracking-tight">
              PHP <span className="text-transparent bg-clip-text bg-gradient-to-r from-accent-cyan to-accent-purple">Supercharged.</span>
            </h1>
            <p className="text-lg md:text-xl text-foreground-muted leading-relaxed">
              DualMind AI OS natively understands, architects, and optimizes PHP ecosystems. 
              From legacy LAMP stacks to modern Laravel applications, unleash autonomous cognition 
              directly into your backend.
            </p>
          </motion.div>
        </div>

        {/* Showcase Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center mb-24">
          
          {/* Action Cards */}
          <motion.div 
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.7, delay: 0.2 }}
            className="flex flex-col gap-6"
          >
            <h2 className="text-2xl font-bold mb-2 flex items-center gap-3">
              <Terminal className="w-6 h-6 text-accent-cyan" />
              Intelligence at the Edge
            </h2>
            
            {QUICK_ACTIONS.map((action, idx) => (
              <div 
                key={idx}
                className="group relative p-6 rounded-2xl bg-glass-overlay border border-border-glass hover:bg-glass-highlight hover:border-accent-cyan/30 transition-all cursor-pointer backdrop-blur-md overflow-hidden"
              >
                <div className="absolute inset-0 bg-gradient-to-r from-accent-cyan/0 via-accent-cyan/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                <div className="relative z-10 flex gap-4 items-start">
                  <div className="p-3 rounded-xl bg-background/50 border border-border-glass shadow-inner">
                    {action.icon}
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold mb-1 group-hover:text-accent-cyan transition-colors">
                      {action.title}
                    </h3>
                    <p className="text-foreground-muted text-sm leading-relaxed">
                      {action.description}
                    </p>
                  </div>
                </div>
              </div>
            ))}

            <button className="mt-4 px-6 py-4 rounded-xl bg-white text-black font-semibold hover:bg-accent-cyan hover:text-white hover:shadow-[0_0_30px_-5px_rgba(45,212,191,0.5)] transition-all flex items-center justify-center gap-2 group w-full md:w-fit">
              <Globe className="w-5 h-5" />
              Launch PHP Agent
              <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
            </button>
          </motion.div>

          {/* Code Window */}
          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.7, delay: 0.4 }}
            className="relative"
          >
            <div className="absolute -inset-1 bg-gradient-to-br from-accent-cyan/20 to-accent-purple/20 rounded-2xl blur-2xl opacity-50" />
            <div className="relative rounded-2xl overflow-hidden border border-border-glass bg-[#0d1117] shadow-2xl backdrop-blur-xl">
              <div className="flex items-center px-4 py-3 bg-[#161b22] border-b border-white/5">
                <div className="flex gap-2">
                  <div className="w-3 h-3 rounded-full bg-red-500/80" />
                  <div className="w-3 h-3 rounded-full bg-yellow-500/80" />
                  <div className="w-3 h-3 rounded-full bg-green-500/80" />
                </div>
                <div className="mx-auto text-xs font-mono text-white/40">IntelligenceController.php</div>
              </div>
              <div className="p-4 overflow-x-auto text-sm">
                <SyntaxHighlighter
                  language="php"
                  style={atomDark}
                  customStyle={{ background: 'transparent', padding: 0, margin: 0 }}
                  wrapLines={true}
                >
                  {PHP_EXAMPLE}
                </SyntaxHighlighter>
              </div>
            </div>
          </motion.div>
          
        </div>
      </div>
      
      <footer className="py-12 text-center border-t border-border-glass bg-glass-overlay backdrop-blur-md">
        <p className="text-foreground-muted">© 2026 DualMind OS. PHP AI Extensions Active.</p>
      </footer>
    </main>
  );
}
